import type { Metadata } from "next";
import { Oxanium, Merriweather, Fira_Code } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const oxanium = Oxanium({ subsets: ["latin"], variable: "--font-oxanium" });
const merriweather = Merriweather({ weight: ["400", "700"], subsets: ["latin"], variable: "--font-merriweather" });
const firaCode = Fira_Code({ subsets: ["latin"], variable: "--font-fira-code" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${oxanium.variable} ${merriweather.variable} ${firaCode.variable}`}
    >
      <body className=" bg-background text-foreground font-sans antialiased">
        <div className="flex min-h-screen">
          <Sidebar />

          <main
            className="flex-1 bg-background
                     flex flex-col
                     overflow-hidden"
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  )

}
