/**
 * Content palette — the only colors user columns/cards may use.
 * Re-spaced so the Ember accent (hue ~48) keeps its own lane: no content
 * hue sits between Crimson(20) and Gold(78).
 */
export const COLUMN_COLORS = [
  { name: "Crimson", value: "oklch(0.68 0.17 20)" },
  { name: "Gold", value: "oklch(0.74 0.14 78)" },
  { name: "Green", value: "oklch(0.70 0.15 145)" },
  { name: "Teal", value: "oklch(0.72 0.13 185)" },
  { name: "Azure", value: "oklch(0.70 0.14 235)" },
  { name: "Violet", value: "oklch(0.66 0.16 292)" },
  { name: "Pink", value: "oklch(0.69 0.17 332)" },
  { name: "Graphite", value: "oklch(0.62 0.008 60)" },
] as const;

export type ContentColor = (typeof COLUMN_COLORS)[number]["value"];

/** Legacy → current palette. Keys are exact strings previously persisted
 *  or generated by older versions (old OKLCH set + hex defaults/demo). */
const LEGACY_COLOR_MAP: Record<string, string> = {
  // v0 OKLCH palette
  "oklch(0.72 0.16 25)": COLUMN_COLORS[0].value,
  "oklch(0.72 0.16 55)": COLUMN_COLORS[1].value,
  "oklch(0.72 0.14 85)": COLUMN_COLORS[1].value,
  "oklch(0.72 0.16 145)": COLUMN_COLORS[2].value,
  "oklch(0.72 0.16 180)": COLUMN_COLORS[3].value,
  "oklch(0.72 0.16 250)": COLUMN_COLORS[4].value,
  "oklch(0.72 0.16 310)": COLUMN_COLORS[5].value,

  // Legacy hex defaults & demo colors
  "#f1f5f9": COLUMN_COLORS[7].value,
  "#e0e7ff": COLUMN_COLORS[5].value,
  "#dbeafe": COLUMN_COLORS[4].value,
  "#fce7f3": COLUMN_COLORS[6].value,
  "#cffafe": COLUMN_COLORS[3].value,
  "#a5f3fc": COLUMN_COLORS[3].value,
  "#e0f2fe": COLUMN_COLORS[4].value,
  "#fef3c7": COLUMN_COLORS[1].value,
  "#fef9c3": COLUMN_COLORS[1].value,
  "#dcfce7": COLUMN_COLORS[2].value,
  "#d1fae5": COLUMN_COLORS[2].value,
  "#bbf7d0": COLUMN_COLORS[2].value,
};

/** Snap a stored/imported color onto the current palette when it matches a
 *  known legacy value; unknown values pass through untouched. */
export function normalizeContentColor(color: string): string {
  return LEGACY_COLOR_MAP[color] ?? color;
}
